### PR TITLE
Now connects to a given address string instead of a port number.

### PR DESCRIPTION
**Pull request by psychoticmeow**
The unit tests will need to be updated later on to run against the same changes to the socket component.

### CODE REVIEW

**Comment by arunpoudel** [comment]
+1

**Comment by clue** [comment]
:+1: on this API!

This is  also in line with how quite a few other APIs accept targets (stream_socket_client() etc.). Also, this makes it quite easy to implement Unix domain socket paths (#37).

Also, I consider this a first step towards simplifying our user-facing API for socket-client: See also #38 for some background. I'm hoping we will eventually accept URLs like:

```
tcp://www.google.com:80
tls://www.google.com:443
unix:///var/tmp/demo.sock
```

**Comment by joelwurtz** [comment]
:+1: Really need this for using unix socket domain, is there some way i can help to have this merged ?

As far as i understand the biggest problem is the BC Break which can be easily fixed by keeping the current api and this implementation and before doing the parsing just use concatenation with $adress:$port.

**Comment by KingCrunch** [comment]
:+1: 

I need UNIX-sockets.

**Comment by clue** [comment]
I assume the main motivation for this change was API consistency rather than Unix domain sockets? Personally, I'm all for API consistency and would probably also want to take a look at the bigger picture while we're at this (#38 discussed this in more detail).

> :+1: Really need this for using unix socket domain, is there some way i can help to have this merged ?

Unix domain sockets are now handled in #37, in particular in the new PR #41. IMO this *can* be resolved without addressing the API inconsistencies first (though it probably makes sense to tackle these afterwards).

**Pull request closed without merging**
